# Generated by Django 4.2 on 2023-04-21 07:14

import baham.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('username', models.CharField(editable=False, max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=512)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('primary_contact', models.CharField(max_length=20)),
                ('alternate_contact', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=255)),
                ('address_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('address_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('landmark', models.CharField(max_length=255)),
                ('town', models.CharField(choices=[('Bin Qasim', 'Bin Qasim'), ('Gadap', 'Gadap'), ('Gulberg', 'Gulberg'), ('Gulshan-e-Iqbal', 'Gulshan-e-Iqbal'), ('Jamshed', 'Jamshed'), ('Keamari', 'Keamari'), ('Korangi', 'Korangi'), ('Landhi', 'Landhi'), ('Liaquatabad', 'Liaquatabad'), ('Malir', 'Malir'), ('New Karachi', 'New Karachi'), ('North Nazimabad', 'North Nazimabad'), ('Orangi', 'Orangi'), ('SITE', 'SITE'), ('Saddar', 'Saddar'), ('Shah Faisal', 'Shah Faisal')], max_length=50)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('date_deactivated', models.DateTimeField(editable=False, null=True)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('model_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=20)),
                ('model', models.CharField(default='Unknown', max_length=20)),
                ('type', models.CharField(choices=[('AUTO_RICKSHAW', 'Auto Rickshaw'), ('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatch Back'), ('SUV', 'Sub-Urban Vehicle'), ('VAN', 'Van'), ('HIGH_ROOF', 'High Roof'), ('MOTORCYCLE', 'Moto cycle/Scooter')], help_text='Select the vehicle chassis type', max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'db_table': 'baham_vehicle_model',
            },
        ),
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baham.user')),
                ('has_contract', models.BooleanField(default=False)),
            ],
            bases=('baham.user',),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baham.user')),
                ('date_joined', models.DateField()),
                ('active_contracts', models.PositiveSmallIntegerField(default=0)),
            ],
            bases=('baham.user',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('registration_number', models.CharField(help_text='Unique registration/license plate no. of the vehicle.', max_length=10, unique=True)),
                ('colour', models.CharField(default='white', max_length=50, validators=[baham.models.validate_colour])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('FULL', 'Full'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], max_length=50)),
                ('picture1', models.ImageField(null=True, upload_to='pictures')),
                ('picture2', models.ImageField(null=True, upload_to='pictures')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baham.vehiclemodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baham.user')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('effective_start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('fuel_share', models.PositiveSmallIntegerField(help_text='Percentage of fuel contribution.')),
                ('maintenance_share', models.PositiveSmallIntegerField(help_text='Percentage of maintenance cost contribution.')),
                ('schedule', models.CharField(max_length=255)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baham.vehicle')),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baham.companion')),
            ],
        ),
    ]
