# All constants used in the system
COLOURS = ['ALICEBLUE', 'ANTIQUEWHITE', 'AQUA', 'AQUAMARINE', 'AZURE', 'BEIGE', 'BISQUE', 'BLACK', 'BLANCHEDALMOND',
           'BLUE', 'BLUEVIOLET', 'BROWN', 'BURLYWOOD', 'CADETBLUE', 'CHARTREUSE', 'CHOCOLATE', 'CORAL',
           'CORNFLOWERBLUE', 'CORNSILK', 'CRIMSON', 'CYAN', 'PINK', 'SKYBLUE', 'DIMGREY', 'DODGERBLUE', 'FIREBRICK',
           'FLORALWHITE', 'FORESTGREEN', 'FUCHSIA', 'GAINSBORO', 'GHOSTWHITE', 'GOLD', 'GOLDENROD',
           'GOLDENRODYELLOW', 'GRAY', 'GREEN', 'GREENYELLOW', 'GREY', 'HONEYDEW', 'HOTPINK', 'INDIANRED', 'INDIGO',
           'IVORY', 'KHAKI', 'LAVENDER', 'LAVENDERBLUSH', 'LAWNGREEN', 'LEMONCHIFFON', 'LIME', 'LIMEGREEN', 'LINEN',
           'MAGENTA', 'MAROON', 'MIDNIGHTBLUE', 'MINTCREAM', 'MISTYROSE', 'MOCCASIN', 'NAVAJOWHITE', 'NAVY',
           'OLDLACE', 'OLIVE', 'OLIVEDRAB', 'OLIVEGREEN', 'ORANGE', 'ORANGERED', 'ORCHID', 'PALEGOLDENROD',
           'PALEGREEN', 'PALETURQUOISE', 'PALEVIOLETRED', 'PAPAYAWHIP', 'PEACHPUFF', 'PERU', 'PLUM', 'POWDERBLUE',
           'PURPLE', 'RED', 'ROSYBROWN', 'ROYALBLUE', 'SADDLEBROWN', 'SALMON', 'SANDYBROWN', 'SEAGREEN', 'SEASHELL',
           'SIENNA', 'SILVER', 'SLATEBLUE', 'SLATEGRAY', 'SLATEGREY', 'SNOW', 'SPRINGGREEN', 'STEELBLUE', 'TAN',
           'TEAL', 'THISTLE', 'TOMATO', 'TURQUOISE', 'VIOLET', 'VIOLETRED', 'WHEAT', 'WHITE', 'WHITESMOKE', 'YELLOW',
           'YELLOWGREEN']

TOWNS = ['Bin Qasim', 'Gadap', 'Gulberg', 'Gulshan-e-Iqbal', 'Jamshed', 'Keamari', 'Korangi', 'Landhi', 'Liaquatabad',
           'Malir', 'New Karachi', 'North Nazimabad', 'Orangi', 'SITE', 'Saddar', 'Shah Faisal']
